// <auto-generated />
namespace THT_Wave_soldering.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class THTWave2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(THTWave2));
        
        string IMigrationMetadata.Id
        {
            get { return "202112030759532_THTWave2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
